version: '3.8'

services: 
  api: 
    build:
      context: ./backend
    container_name: api
    ports:
      - 8080:8080
    environment: 
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    command: tail -F /none
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./dbvolumes/mongo:/data/db
  postgres:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_NAME
    ports:
      - 6543:5432
    volumes:
      - ./dbvolumes/postgres:/var/lib/postgresql/data
  cache:
    image: redis
    container_name: cache
    ports: 
      - 6379:6379